### ISSUE TITLE
C4 config training error

### ISSUE THREAD

**Issue by Retiina** [TuSimple/simpledet#123]
I want to train `faster_r50v1c4_c5_512roi_1x.py` on **8 v100**, but there is an error:

```
Traceback (most recent call last):
  File "detection_train.py", line 272, in <module>
    train_net(parse_args())
  File "detection_train.py", line 256, in train_net
    profile=profile
  File "/simpledet/tmp/simpledet/core/detection_module.py", line 994, in fit
    self.update()
  File "/simpledet/tmp/simpledet/core/detection_module.py", line 679, in update
    self._kvstore, self._exec_group.param_names)
  File "/anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/model.py"
, line 158, in _update_params_on_kvstore
    kvstore.push(name, grad_list, priority=-index)
  File "/anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/kvstore.p
y", line 234, in push
    self.handle, mx_uint(len(ckeys)), ckeys, cvals, ctypes.c_int(priority)))
  File "/anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/base.py"$ line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:55:17] src/storage/./pinned_memory_storage.h:62: Check failed: e == cudaSuccess || e == cuda$rrorCudartUnloading: CUDA: an illegal memory access was encountered
Stack trace:
  [bt] (0) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxn
et.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x22) [0x7f2834448e82]
  [bt] (1) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxn
et.so(mxnet::storage::PinnedMemoryStorage::Alloc(mxnet::Storage::Handle*)+0x104) [0x7f283637a0b4]
  [bt] (2) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxn
et.so(mxnet::StorageImpl::Alloc(mxnet::Storage::Handle*)+0x47) [0x7f2836373837]
  [bt] (3) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxn
et.so(std::__shared_ptr<mxnet::NDArray::Chunk, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<mxnet::NDArray::
Chunk>, mxnet::TShape const&, mxnet::Context&, bool&, int&>(std::_Sp_make_shared_tag, std::allocator<mxnet::NDArray::Chu
nk> const&, mxnet::TShape const&, mxnet::Context&, bool&, int&)+0x2a2) [0x7f283647a212]
  [bt] (4) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxn
et.so(+0x30503a9) [0x7f28364543a9]
  [bt] (5) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxnet.so(mxnet::kvstore::CommCPU::Reduce(int, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, int)+0xb
da) [0x7f28364bc11a]
  [bt] (6) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxnet.so(mxnet::kvstore::KVStoreLocal::PushImpl(std::vector<int, std::allocator<int> > const&, std::vector<mxnet::NDArray,
std::allocator<mxnet::NDArray> > const&, int)+0x1a9) [0x7f28364cf099]
  [bt] (7) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxn
et.so(mxnet::kvstore::KVStoreLocal::Push(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&,
 std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, int)+0xb6) [0x7f283647d876]
  [bt] (8) /anaconda3/envs/simpledet/lib/python3.7/site-packages/mxnet-1.5.0-py3.7.egg/mxnet/libmxnet.so(MXKVStorePushEx+0x4ae) [0x7f28363e5cae]
```

Could you  give me some advice, thanks in advance!

**Comment by RogerChern** [comment]
Could you please include your environment information?

**Comment by Retiina** [comment]
My environment is as follow: 8 v100s, cuda 9, cudnn 7.0.4, nvidia-drive 390.3.

**Comment by RogerChern** [comment]
Sorry, we can not reproduce this bug. Maybe you can try out the provided docker image to see if this persists.
