### ISSUE TITLE
Train custom data failed because of rpn_head.get_loss

### ISSUE THREAD

**Issue by 1224wxwx** [TuSimple/simpledet#159]
Traceback (most recent call last):                  
                                                                                                                    File "detection_train.py", line 276, in                                                                                                                         train_net(parse_args())                                                                                                                                             File "detection_train.py", line 21, in train_net                                                                                                                        transform, data_name, label_name, metric_list = config.get_config(is_train=True)             
                                                                       File "/simpledet/simpledet/simpledet/config/tridentnet_r101v2c4_c5_1x_mine.py", line 133, in get_config                                                                 num_branch=Trident.num_branch, scaleaware=Trident.train_scaleaware)            
                                                                                     File "/simpledet/simpledet/simpledet/models/tridentnet/builder.py", line 84, in get_train_symbol                                                                        rpn_loss = rpn_head.get_loss(rpn_feat, rpn_cls_label, rpn_reg_target, rpn_reg_weight)                                                                             TypeError: get_loss() takes 4 positional arguments but 5 were given

I generated roidb for my custom data and chose tridentnet to train, but I got errors like this. Could you please tell me how to train custom data?

**Comment by 1224wxwx** [comment]
Just fixed this bug several hours ago.

**Comment by dl19940602** [comment]
@1224wxwx Hi,do you train your own dataset?could you tell me which code dou you modify based on your own datasets?Thank you!
