### ISSUE TITLE
Training cascade_rcnn failed because of get_loss

### ISSUE THREAD

**Issue by 1224wxwx** [TuSimple/simpledet#161]
Traceback (most recent call last):          
                                                                                                                            File "detection_train.py", line 277, in                                                                                                                         train_net(parse_args())           
                                                                                                                                  File "detection_train.py", line 21, in train_net                                                                                                                        transform, data_name, label_name, metric_list = config.get_config(is_train=True)    
                                                                                File "/simpledet/simpledet/simpledet/config/cascade_r101v1_fpn_1x_mine.py", line 198, in get_config                                                                     bbox_head_3rd                    
                                                                                                                                   File "/simpledet/simpledet/simpledet/models/cascade_rcnn/builder.py", line 28, in get_train_symbol                                                                      rpn_loss = rpn_head.get_loss(rpn_feat, rpn_cls_label, rpn_reg_target, rpn_reg_weight)        
                                                                     TypeError: get_loss() takes 4 positional arguments but 5 were given

Hi, I used cascade_r101v1_fpn_1x as my model to train custom data, but got error like this.

**Comment by RogerChern** [comment]
Bug confirmed and I am working on it.

**Comment by RogerChern** [comment]
Close by #162
