### ISSUE TITLE
NASFPN test errors, when I run the test file of NASFPN , the error is " 'Results do not correspond to current coco set'"

### ISSUE THREAD

**Issue by easycome2009** [TuSimple/simpledet#165]
As mentioned in the title, I do not change any params of the configuration file, the results json filesand  coco json file exsited . however the img-id are not matched. I do not known why ? Help!!!
I am using ubuntu16.04 cuda9.2. Before this error occur, I fix another bug that 'Check failed: to->type_flag_ == from.type_flag_ (0 vs. 6) : Source and targe', anyone else met this problem,too?
The Traceback information is shown below:

Traceback (most recent call last):
  File "/home/dongdong/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/dongdong/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 434, in main
    run()
  File "/home/dongdong/.vscode/extensions/ms-python.python-2019.6.24221/pythonFiles/lib/python/ptvsd/__main__.py", line 312, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/dongdong/anaconda3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/dongdong/anaconda3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/dongdong/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dongdong/dd/simpledet/detection_test1.py", line 57, in <module>
    coco_dt,coco_dat = coco.loadRes("/home/dongdong/dd/simpledet/experiments/retina_r50v1b_nasfpn_640_7@256_25epoch/coco_test-dev2017_result.json")
  File "/home/dongdong/anaconda3/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 326, in loadRes
    'Results do not correspond to current coco set'
AssertionError: Results do not correspond to current coco set

**Comment by xchani** [comment]
Replace ```coco_test-dev2017``` by ```coco_minival2014``` in config file, since there is no valid label for **testdev**.

**Comment by RogerChern** [comment]
Hi, @easycome2009,
In order to evaluate the `coco_test-dev2017` set, you need to submit the `coco_test-dev2017_result.json` to [codalab](https://competitions.codalab.org/competitions/5181#participate) since no one has the label of the `test-dev` set.
