### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by danfouer** [TuSimple/simpledet#18]
ubuntu 16.04
python3.5
Device 0: "GeForce GTX 1070"
  CUDA Driver Version / Runtime Version          9.2 / 9.2
  CUDA Capability Major/Minor version number:    6.1
echo "USE_OPENCV = 0" >> ./config.mk
echo "USE_BLAS = openblas" >> ./config.mk
echo "USE_CUDA = 1" >> ./config.mk
echo "USE_CUDA_PATH = /usr/local/cuda" >> ./config.mkg
echo "USE_CUDNN = 1" >> ./config.mk
echo "USE_NCCL = 1" >> ./config.mk
echo "USE_DIST_KVSTORE = 1" >> ./config.mk

after all these horrible things,I only got  

> **### Segmentation fault (core dumped)**

 from python3 detection_train.py --config config/detection_config.py

**Comment by RogerChern** [comment]
The information provided is not suffient for us locate the cause of core dump. Could you please try to setup with pre-built [singualrity image](https://github.com/TuSimple/simpledet/blob/master/doc/INSTALL.md#setup-with-singularity) or docker image and see if this still persists.

**Comment by danfouer** [comment]
I had tried to setup with pre-built singualrity image, and I got Undefined Symbols  error,I guess it may due to mxnext:

Deploy dependency and compile extension

    setup mxnext, a wrapper of mxnet symbolic API

git clone https://github.com/RogerChern/mxnext

    run make in simpledet directory to install cython extensions

But how to setup mxnext after git clone it?

**Comment by huangzehao** [comment]
@danfouer 
You don't need to setup mxnext. Simply git clone is ok.

**Comment by danfouer** [comment]
docker image works! @RogerChern Thank you! 
New problem: TypeError: 'NoneType' object is not subscriptable

root@c952bbf32363:/data/simpledet# python3 detection_train.py --config config/tridentnet_r50v2c4_c5_1x.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/data/simpledet/core/detection_input.py", line 656, in worker
    trans.apply(roi_record)
  File "/data/simpledet/core/detection_input.py", line 37, in apply
    input_record["image"] = image[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

**Comment by huangzehao** [comment]
@danfouer 
Did you prepare data following https://github.com/TuSimple/simpledet#preparing-data?
Please confirm that you can get image array in input_record["image"].

**Comment by RogerChern** [comment]
Please file the roidb issue in a separate thread.

**Comment by vicchu** [comment]
Similar problem:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/simpledet/core/detection_input.py", line 681, in worker
    trans.apply(roi_record)
  File "/simpledet/core/detection_input.py", line 37, in apply
    input_record["image"] = image[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/simpledet/core/detection_input.py", line 681, in worker
    trans.apply(roi_record)
  File "/simpledet/core/detection_input.py", line 37, in apply
    input_record["image"] = image[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

06-21 21:54:17 parameter shape
06-21 21:54:18 [('data', (1, 3, 800, 1200)),
 ('bn_data_gamma', (3,)),
 ('bn_data_beta', (3,)),
...............................
...............................

06-21 21:59:15 Initialized stage4_unit3_bn2_moving_mean as ["zero", {}]: 0.0
06-21 21:59:16 Initialized stage4_unit3_bn2_moving_var as ["one", {}]: 1.0
06-21 21:59:16 Initialized stage4_unit3_bn3_moving_mean as ["zero", {}]: 0.0
06-21 21:59:16 Initialized stage4_unit3_bn3_moving_var as ["one", {}]: 1.0
[13:59:52] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
find_frame: frame not found.
    Looking for thread_id:pid_5584_id_140236295235904, frame_id:140230145378504
    Current     thread_id:pid_5584_id_140236295235904, available frames:
    140231017808792  -  140231017784280  -  140225649053288  -  140229944134264  -  140225380649528
140225447730552  -  140230548005880  -  140230950654120  -  140231677220376  -  140230950652120
140231868347416  -  

    find_frame: frame not found.
    Looking for thread_id:pid_5584_id_140236295235904, frame_id:140230145378504
    Current     thread_id:pid_5584_id_140236295235904, available frames:
    140231017808792  -  140224239838312  -  140229944045112  -  140225649053288  -  140229944134264
140225380649528  -  140225447730552  -  140230548005880  -  140230950654120  -  140231677220376
140230950652120  -  140231868347416  -  

    Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/simpledet/core/detection_input.py", line 681, in worker
    trans.apply(roi_record)
  File "/simpledet/core/detection_input.py", line 37, in apply
    input_record["image"] = image[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/simpledet/core/detection_input.py", line 681, in worker
    trans.apply(roi_record)
  File "/simpledet/core/detection_input.py", line 37, in apply
    input_record["image"] = image[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/simpledet/core/detection_input.py", line 681, in worker
    trans.apply(roi_record)
  File "/simpledet/core/detection_input.py", line 37, in apply
    input_record["image"] = image[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/simpledet/core/detection_input.py", line 681, in worker
    trans.apply(roi_record)
  File "/simpledet/core/detection_input.py", line 37, in apply
    input_record["image"] = image[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable
