### ISSUE TITLE
ModuleNotFoundError: No module named 'mxnext.tvm' #13

### ISSUE THREAD

**Issue by maiff** [TuSimple/simpledet#201]
I use the 'Setup with Docker' and I have run the following command
```
cd $SIMPLEDET_DIR
pip install git+https://github.com/RogerChern/mxnext#egg=mxnext
make
```
but I still got this error when I run `python3 detection_train.py --config config/detection_config.py`
```
Traceback (most recent call last):
  File "detection_train.py", line 277, in <module>
    train_net(parse_args())
  File "detection_train.py", line 272, in parse_args
    config = importlib.import_module(args.config.replace('.py', '').replace('/', '.'))
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/simpledet/config/tridentnet_r101v1c4_c5_1x.py", line 1, in <module>
    from models.tridentnet.builder import TridentFasterRcnn as Detector
  File "/simpledet/models/tridentnet/builder.py", line 5, in <module>
    import mxnext as X
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnext/__init__.py", line 1, in <module>
    from .simple import *
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnext/simple.py", line 372, in <module>
    from mxnext.tvm.decode_bbox import decode_bbox as _decode_bbox
ModuleNotFoundError: No module named 'mxnext.tvm'
```

I pull docker image by this
```
nvidia-docker run -it -v $HOST-SIMPLEDET-DIR:$CONTAINER-WORKDIR registry.cn-beijing.aliyuncs.com/rogerchen/simpledet:cuda10 zsh
```

**Comment by RogerChern** [comment]
Sorry for the inconvenience, please reinstall the mxnext with
```pip install --force-reinstall git+https://github.com/RogerChern/mxnext#egg=mxnext```

**Comment by maiff** [comment]
thanks fix it！
