### ISSUE TITLE
I use my own dataset which is format like coco

### ISSUE THREAD

**Issue by maiff** [TuSimple/simpledet#202]
I had run `python3 utils/generate_roidb.py --dataset coco --dataset-split mydataset`, I got no error, but when I run `python3 detection_train.py --config config/detection_config.py
`
I got this error 
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tbtb/simpledet/core/detection_input.py", line 730, in worker
    trans.apply(roi_record)
  File "/tbtb/simpledet/core/detection_input.py", line 316, in apply
    padded_gt_bbox[:len(gt_bbox)] = gt_bbox
ValueError: could not broadcast input array from shape (158,5) into shape (100,5)
```

I have modified generate_roidb.py and I add one line to dataset_split_mapping to adapt.meanwhile I have changed the config. so I think dataset path is no problem

**Comment by RogerChern** [comment]
Consider changing the `max_num_gt` filed accordingly.
https://github.com/TuSimple/simpledet/blob/280b8510f7633628f2b987ed6d90662f6a394024/config/cascade_r101v1_fpn_1x.py#L282-L285

**Comment by paklau99988** [comment]
I have the same error. I changed 100 to 105. But then I got the error again with 101 and a core dunp. 

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/simple/simpledet/core/detection_input.py", line 725, in worker
    trans.apply(roi_record)
  File "/root/sharedfolder/simple/simpledet/core/detection_input.py", line 315, in apply
    padded_gt_bbox[:len(gt_bbox)] = gt_bbox
ValueError: could not broadcast input array from shape (101,5) into shape (100,5)

07-12 15:14:26 Epoch[0] Batch [50]      Iter: 50/4548   Lr: 0.00400     Speed: 18.94 samples/sec        Train-RpnAcc=0.842869,  RpnL1=0.360510, RcnnAcc=0.817187,       RcnnL1=1.481765,
07-12 15:14:30 Epoch[0] Batch [60]      Iter: 60/4548   Lr: 0.00413     Speed: 18.86 samples/sec        Train-RpnAcc=0.858823,  RpnL1=0.352146, RcnnAcc=0.827028,       RcnnL1=1.476584,
07-12 15:14:34 Epoch[0] Batch [70]      Iter: 70/4548   Lr: 0.00427     Speed: 18.66 samples/sec        Train-RpnAcc=0.871417,  RpnL1=0.345748, RcnnAcc=0.835504,       RcnnL1=1.456253,
07-12 15:14:39 Epoch[0] Batch [80]      Iter: 80/4548   Lr: 0.00440     Speed: 18.74 samples/sec        Train-RpnAcc=0.881336,  RpnL1=0.338987, RcnnAcc=0.841628,       RcnnL1=1.451213,
07-12 15:14:43 Epoch[0] Batch [90]      Iter: 90/4548   Lr: 0.00453     Speed: 19.23 samples/sec        Train-RpnAcc=0.889799,  RpnL1=0.336308, RcnnAcc=0.848507,       RcnnL1=1.441484,
07-12 15:14:47 Epoch[0] Batch [100]     Iter: 100/4548  Lr: 0.00467     Speed: 18.93 samples/sec        Train-RpnAcc=0.896397,  RpnL1=0.329345, RcnnAcc=0.854231,       RcnnL1=1.420899,
07-12 15:14:51 Epoch[0] Batch [110]     Iter: 110/4548  Lr: 0.00480     Speed: 18.62 samples/sec        Train-RpnAcc=0.902405,  RpnL1=0.322144, RcnnAcc=0.859630,       RcnnL1=1.404732,

Segmentation fault: 11

Segmentation fault (core dumped)


```
