### ISSUE TITLE
pulled docker and followed install guide, no module mxnext

### ISSUE THREAD

**Issue by lclalalalala** [TuSimple/simpledet#28]
ModuleNotFoundError: No module named 'mxnext'
what is mxnext?

**Comment by lclalalalala** [comment]
`root@b898ea5c16c9 ~/simpledet# python3 detection_train.py --config config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py
Traceback (most recent call last):
  File "detection_train.py", line 229, in <module>
    train_net(parse_args())
  File "detection_train.py", line 224, in parse_args
    config = importlib.import_module(args.config.replace('.py', '').replace('/', '.'))
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/simpledet/config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py", line 1, in <module>
    from models.tridentnet.builder import TridentFasterRcnn as Detector
  File "/root/simpledet/models/tridentnet/builder.py", line 5, in <module>
    import mxnext as X
ModuleNotFoundError: No module named 'mxnext'`

**Comment by lclalalalala** [comment]
`shell
root@b898ea5c16c9 ~/simpledet# python3 detection_train.py --config config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py
Traceback (most recent call last):
  File "detection_train.py", line 229, in <module>
    train_net(parse_args())
  File "detection_train.py", line 224, in parse_args
    config = importlib.import_module(args.config.replace('.py', '').replace('/', '.'))
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/simpledet/config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py", line 1, in <module>
    from models.tridentnet.builder import TridentFasterRcnn as Detector
  File "/root/simpledet/models/tridentnet/builder.py", line 5, in <module>
    import mxnext as X
ModuleNotFoundError: No module named 'mxnext'`

**Comment by lclalalalala** [comment]
`root@b898ea5c16c9 ~/simpledet# python3 detection_train.py --config config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py
Traceback (most recent call last):
  File "detection_train.py", line 229, in <module>
    train_net(parse_args())
  File "detection_train.py", line 224, in parse_args
    config = importlib.import_module(args.config.replace('.py', '').replace('/', '.'))
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/simpledet/config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py", line 1, in <module>
    from models.tridentnet.builder import TridentFasterRcnn as Detector
  File "/root/simpledet/models/tridentnet/builder.py", line 5, in <module>
    import mxnext as X
ModuleNotFoundError: No module named 'mxnext'`

**Comment by mrbulb** [comment]
I the `README.md` , it mention the `mxnext`
> Deploy dependency and compile extension
> 1. setup mxnext, a wrapper of mxnet symbolic API
> ```shell
>    git clone https://github.com/RogerChern/mxnext
> ```
> 2. run make in simpledet directory to install cython extensions

after run docker file, you may need to install `mxnext` manually according to `README.md`

**Comment by lclalalalala** [comment]
Thank you very much! I am so unobservant. I thought everything is in 

> install.md
