### ISSUE TITLE
run create_voc_roidb.py

### ISSUE THREAD

**Issue by MTfast** [TuSimple/simpledet#282]
I want to train my own dataset using tridentnet. I convert my voc-format dataset to roidb and run create_voc_roidb.py 
the following error：
Traceback (most recent call last):
  File "utils/create_voc_roidb.py", line 80, in <module>
    create_roidb(*parse_args())
  File "utils/create_voc_roidb.py", line 19, in parse_args
    with open(args.label_map) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/label_map/voc_label_map.json'

voc-format dataset don't have files in json format...

**Comment by RogerChern** [comment]
You may need a label map json file to map your classname to train id.

https://github.com/TuSimple/simpledet/blob/f67fca08b33d957b43eb1db5e3745a3a9e3803b5/utils/create_voc_roidb.py#L52

**Comment by MTfast** [comment]
What is the format of this json file?

**Comment by RogerChern** [comment]
Just plain kv pairs as
{ "category_name": train_id }

**Comment by dongjuns** [comment]
Hi, how can I make that voc_label_map.json?
could you know that?

**Comment by dongjuns** [comment]
Here are some codes for making that.

```
import os
import json
import cv2

path = os.getcwd()
print(path)
datasetList = os.listdir(os.path.join(path, "dataset"))
print(datasetList)
annotationsList = os.listdir(os.path.join(path, "annotations"))
print(annotationsList)

jsonDataList = []
jsonData = {}
datasetList.sort()
annotationsList.sort(key=int)
count = 0
for dataset in datasetList:
    count += 1
    img_url = dataset
    fileName = dataset.split(".")[0]
            
    annotations = []
    bboxes = []
    for annotation in annotationsList:
        antn = "_".join(annotation.split("_", 2)[:2])
        antnRest = "_".join(annotation.split("_", 2)[2:])
        if len(annotations) == 12:
            break
        elif fileName == antn:
            annotations.append(int(antnRest)+1)
            f = open(os.path.join("./annotations/", annotation), "r")
            bbox = f.read()[:-1]
            bbox_split = bbox.split(",")
            bbox_map = map(int, bbox_split)
            bbox_ = list(bbox_map)
            bboxes.append(bbox_)
            f.close()
        else:
            continue
            
    image_url = os.path.join(path, "dataset", img_url)
    img = cv2.imread(image_url)
    height, width = img.shape[:2]
    jsonData = {
        "gt_class": annotations,
        "gt_bbox": bboxes,
        "flipped": False,
        "h": height,
        "w": width,
        "image_url": image_url,
        "im_id": count
    }
    jsonDataList.append(jsonData)
    
with open("voc_label_map.json", "w") as write_file:
    json.dump(jsonDataList, write_file)

```
