### ISSUE TITLE
运行detection_test.py报错

### ISSUE THREAD

**Issue by dongzhenguo2016** [TuSimple/simpledet#293]
我在运行detection_test.py的时候，报了下面的错，请问该怎么解决呀？谢谢
Traceback (most recent call last):
  File "/home/hdc/anaconda3/envs/simpledet/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/hdc/data1/dzc/simpledet/detection_test.py", line 301, in <module>
    coco_eval = COCOeval(coco, coco_dt)
  File "/home/hdc/anaconda3/envs/simpledet/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 76, in __init__
    self.params = Params(iouType=iouType) # parameters
  File "/home/hdc/anaconda3/envs/simpledet/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 527, in __init__
    self.setDetParams()
  File "/home/hdc/anaconda3/envs/simpledet/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 507, in setDetParams
    self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/hdc/anaconda3/envs/simpledet/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by huangzehao** [comment]
Hi, here offer two solutions:
1. pip install numpy==1.17 and return test code
or 
2.  modify np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True) into np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05) + 1), endpoint=True) and rerun test code

**Comment by dongzhenguo2016** [comment]
> Hi, here offer two solutions:
> 
> 1. pip install numpy==1.17 and return test code
>    or
> 2. modify np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True) into np.linspace(.5, 0.95, int(np.round((0.95 - .5) / .05) + 1), endpoint=True) and rerun test code

非常感谢你，问题按照你说的解决方案解决了。谢谢你
