### ISSUE TITLE
RuntimeError: simple_bind error. Arguments:

### ISSUE THREAD

**Issue by TimLiujn** [TuSimple/simpledet#316]
when i train my own dataset in single gpu,the following is the wrong report.:
Traceback (most recent call last):
  File "/home/ljn/ljn_work/simpledet/detection_train.py", line 313, in <module>
    train_net(parse_args())
  File "/home/ljn/ljn_work/simpledet/detection_train.py", line 295, in train_net
    profile=profile
  File "/home/ljn/ljn_work/simpledet/core/detection_module.py", line 969, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/ljn/ljn_work/simpledet/core/detection_module.py", line 450, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python3.6/site-packages/mxnet-1.6.0-py3.6.egg/mxnet/module/executor_group.py", line 280, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python3.6/site-packages/mxnet-1.6.0-py3.6.egg/mxnet/module/executor_group.py", line 376, in bind_exec
    shared_group))
  File "/usr/local/lib/python3.6/site-packages/mxnet-1.6.0-py3.6.egg/mxnet/module/executor_group.py", line 670, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python3.6/site-packages/mxnet-1.6.0-py3.6.egg/mxnet/symbol/symbol.py", line 1782, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (1, 3, 800, 1200)
im_info: (1, 3)
gt_bbox: (1, 100, 5)
valid_ranges: (1, 3, 2)
rpn_cls_label: (1, 3, 56250)
rpn_reg_target: (1, 3, 60, 50, 75)
rpn_reg_weight: (1, 3, 60, 50, 75)
Traceback (most recent call last):
  File "src/operator/contrib/./../tensor/.././operator_common.h", line 404
MXNetError: Check failed: p->num_inputs() == p->inputs.size() (1 vs. 4) : Number of inputs to operator _backward_ROIAlign_v2 (1) does not match the actual number of inputs provided to operator roi_align_backward (4).

**Comment by huangzehao** [comment]
Can you train COCO sucessfully?

**Comment by TimLiujn** [comment]
> Can you train COCO sucessfully?

Yes,this error is due to the mxnet version problem
