### ISSUE TITLE
 python3 detection_train.py --config config/retina_r50v1_fpn_1x.py error

### ISSUE THREAD

**Issue by lucheng07082221** [TuSimple/simpledet#44]
python3 detection_train.py --config config/retina_r50v1_fpn_1x.py
[Warning] Your mxnet does not support ProposalTarget
[Warning] Your mxnet does not support DecodeBBox
[Warning] Your mxnet does not support BBoxNorm
[Warning] Your mxnet does not support FocalLoss
Traceback (most recent call last):
  File "detection_train.py", line 229, in <module>
    train_net(parse_args())
  File "detection_train.py", line 21, in train_net
    transform, data_name, label_name, metric_list = config.get_config(is_train=True)
  File "/home/lc/work/simpledet/config/retina_r50v1_fpn_1x.py", line 112, in get_config
    train_sym = detector.get_train_symbol(backbone, neck, rpn_head)
  File "/home/lc/work/simpledet/models/retinanet/builder.py", line 23, in get_train_symbol
    loss = head.get_loss(feat, rpn_cls_label, rpn_reg_target, rpn_reg_weight)
  File "/home/lc/work/simpledet/models/retinanet/builder.py", line 275, in get_loss
    cls_loss = X.focal_loss(
AttributeError: module 'mxnext' has no attribute 'focal_loss'

but in my folder:/home/lc/work/simpledet/operator_cxx/contrib has focal_loss.cc focal_loss.cu focal_loss.o

**Comment by RogerChern** [comment]
Please refer to #43
