### ISSUE TITLE
Error when training Retinanet with FP16

### ISSUE THREAD

**Issue by LightToYang** [TuSimple/simpledet#59]
```
Traceback (most recent call last):
  File "detection_train.py", line 229, in <module>
    train_net(parse_args())
  File "detection_train.py", line 213, in train_net
    num_epoch=end_epoch
  File "/media/ycg/experiment/workspace/simpledet/core/detection_module.py", line 959, in fit
    for_training=True, force_rebind=force_rebind)
  File "/media/ycg/experiment/workspace/simpledet/core/detection_module.py", line 440, in bind
    state_names=self._state_names)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/home/ycg/anaconda3/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/symbol/symbol.py", line 1608, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
data: (2, 3, 800, 1333)
rpn_cls_label: (2, 200700)
rpn_reg_target: (2, 36, 22300)
rpn_reg_weight: (2, 36, 22300)
Error in operator P4_clip: [13:18:18] include/mxnet/operator.h:228: Check failed: in_type->at(i) == mshadow::default_type_flag || in_type->at(i) == -1 Unsupported data type 2
```

**Comment by LightToYang** [comment]
Training with FP32 is alright
```
[13:12:27] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
04-01 13:12:37 Epoch[0] Batch [10]	Speed: 8.39 samples/sec	Train-FGAcc=0.024091,	
04-01 13:12:41 Epoch[0] Batch [20]	Speed: 9.79 samples/sec	Train-FGAcc=0.056045,	
04-01 13:12:45 Epoch[0] Batch [30]	Speed: 9.49 samples/sec	Train-FGAcc=0.096019,	
04-01 13:12:49 Epoch[0] Batch [40]	Speed: 9.77 samples/sec	Train-FGAcc=0.119004,	
04-01 13:12:53 Epoch[0] Batch [50]	Speed: 9.71 samples/sec	Train-FGAcc=0.145620,	
04-01 13:12:57 Epoch[0] Batch [60]	Speed: 9.72 samples/sec	Train-FGAcc=0.167263,	
04-01 13:13:02 Epoch[0] Batch [70]	Speed: 9.55 samples/sec	Train-FGAcc=0.176828,	
04-01 13:13:06 Epoch[0] Batch [80]	Speed: 9.78 samples/sec	Train-FGAcc=0.198158,	
04-01 13:13:10 Epoch[0] Batch [90]	Speed: 9.67 samples/sec	Train-FGAcc=0.219836,	
04-01 13:13:14 Epoch[0] Batch [100]	Speed: 9.80 samples/sec	Train-FGAcc=0.238566,	
04-01 13:13:18 Epoch[0] Batch [110]	Speed: 9.56 samples/sec	Train-FGAcc=0.241753,	
04-01 13:13:22 Epoch[0] Batch [120]	Speed: 9.85 samples/sec	Train-FGAcc=0.246967,	
04-01 13:13:26 Epoch[0] Batch [130]	Speed: 9.79 samples/sec	Train-FGAcc=0.251462,	
04-01 13:13:30 Epoch[0] Batch [140]	Speed: 9.78 samples/sec	Train-FGAcc=0.255358,	
04-01 13:13:35 Epoch[0] Batch [150]	Speed: 9.30 samples/sec	Train-FGAcc=0.255080,	
04-01 13:13:39 Epoch[0] Batch [160]	Speed: 9.64 samples/sec	Train-FGAcc=0.259210,	
04-01 13:13:43 Epoch[0] Batch [170]	Speed: 9.59 samples/sec	Train-FGAcc=0.258594,	
04-01 13:13:47 Epoch[0] Batch [180]	Speed: 9.56 samples/sec	Train-FGAcc=0.248346,	
04-01 13:13:51 Epoch[0] Batch [190]	Speed: 9.57 samples/sec	Train-FGAcc=0.236842,	
04-01 13:13:55 Epoch[0] Batch [200]	Speed: 9.85 samples/sec	Train-FGAcc=0.228295,	
04-01 13:14:00 Epoch[0] Batch [210]	Speed: 9.93 samples/sec	Train-FGAcc=0.228522,	
04-01 13:14:04 Epoch[0] Batch [220]	Speed: 9.22 samples/sec	Train-FGAcc=0.228201,	
04-01 13:14:08 Epoch[0] Batch [230]	Speed: 9.52 samples/sec	Train-FGAcc=0.234525,	
04-01 13:14:12 Epoch[0] Batch [240]	Speed: 9.97 samples/sec	Train-FGAcc=0.235065,	
04-01 13:14:16 Epoch[0] Batch [250]	Speed: 9.46 samples/sec	Train-FGAcc=0.236273,	
04-01 13:14:21 Epoch[0] Batch [260]	Speed: 9.40 samples/sec	Train-FGAcc=0.235179,	
04-01 13:14:25 Epoch[0] Batch [270]	Speed: 9.75 samples/sec	Train-FGAcc=0.236178,	
04-01 13:14:29 Epoch[0] Batch [280]	Speed: 9.54 samples/sec	Train-FGAcc=0.240233,	
04-01 13:14:33 Epoch[0] Batch [290]	Speed: 9.68 samples/sec	Train-FGAcc=0.244474,	
04-01 13:14:37 Epoch[0] Batch [300]	Speed: 9.40 samples/sec	Train-FGAcc=0.246605,	
04-01 13:14:41 Epoch[0] Batch [310]	Speed: 9.75 samples/sec	Train-FGAcc=0.247035,	
04-01 13:14:46 Epoch[0] Batch [320]	Speed: 9.50 samples/sec	Train-FGAcc=0.246861,	
04-01 13:14:50 Epoch[0] Batch [330]	Speed: 9.84 samples/sec	Train-FGAcc=0.245453,	
04-01 13:14:54 Epoch[0] Batch [340]	Speed: 9.73 samples/sec	Train-FGAcc=0.246533,	
04-01 13:14:58 Epoch[0] Batch [350]	Speed: 9.65 samples/sec	Train-FGAcc=0.242884,	
04-01 13:15:02 Epoch[0] Batch [360]	Speed: 10.06 samples/sec	Train-FGAcc=0.244113,	
```

**Comment by LightToYang** [comment]
Test retinanet wiht fp16 also occured same error

**Comment by xchani** [comment]
Currently RetinaNet symbol is not prepared for FP16 training/testing, we will update it soon.

**Comment by Hanson0910** [comment]
Hi xchani,can i install simpledet with Ubuntu14.04?

**Comment by xchani** [comment]
@LightToYang refer to #64
