### ISSUE TITLE
2080ti and cuda10 support?

### ISSUE THREAD

**Issue by qixuxiang** [TuSimple/simpledet#77]
Thanks for the amazing work!

I wonder whether simpledet supports 2080ti.

I finish all install steps in my ubuntu16.04 PC with 2*2080ti GPU, when I install cuda9 with cudnn7.2, `python3 detection_train.py --config config/retina_r50v1_fpn_1x.py ` will have error `mxnet.base.MXNetError: [11:35:30] src/operator/nn/./cudnn/cudnn_convolution-inl.h:159: Check failed: e == CUDNN_STATUS_SUCCESS (8 vs. 0) cuDNN: CUDNN_STATUS_EXECUTION_FAILED`

Some people discuss the issue in [mxnet报错: cuDNN: CUDNN_STATUS_EXECUTION_FAILED](https://discuss.gluon.ai/t/topic/10270), so I uninstall cuda9 and install cuda10 with cudnn7.4, but still not work.

Could you please give me some suggestions? Thanks a lot!

**Comment by qixuxiang** [comment]
I solve it  by shielding  cudnn in in mxnet source code:

In `CMakeLists.txt` I set  `mxnet_option(USE_CUDNN            "Build with cudnn support"  OFF)`  

and in `Makefile` change from line 199-202:
```
#ifeq ($(USE_CUDNN), 1)
#	CFLAGS += -DMSHADOW_USE_CUDNN=1
#	LDFLAGS += -lcudnn
#endif
```

**Comment by qixuxiang** [comment]
After shielding cudnn, I still meet a problem

 `mxnet.base.MXNetError: [16:31:25] src/operator/nn/./convolution-inl.h:179: Check failed: req[conv::kOut] == kWriteTo (0 vs. 1) `, 

**and I only meet this problem when** I run `python detection_train.py --config config/tridentnet_r101v2c4_c5_multiscale_addminival_3x_fp16.py`,

**I can run** `python detection_train.py --config config/tridentnet_r101v2c4_c5_addminival_2x.py` and

 `python detection_train.py --config config/ tridentnet_r101v2c4_c5_fastapprox_1x.py` without this problem.

details are below:
```
Traceback (most recent call last):
  File "detection_train.py", line 230, in <module>
    train_net(parse_args())
  File "detection_train.py", line 214, in train_net
    num_epoch=end_epoch
  File "/home/yang/ADTSR/core/detection_module.py", line 995, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/yang/ADTSR/core/detection_module.py", line 783, in update_metric
    self._exec_group.update_metric(eval_metric, labels, pre_sliced)
  File "/home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/module/executor_group.py", line 639, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/metric.py", line 304, in update_dict
    metric.update_dict(labels, preds)
  File "/home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/metric.py", line 132, in update_dict
    self.update(label, pred)
  File "/home/yang/ADTSR/core/detection_metric.py", line 41, in update
    pred_label = mx.ndarray.argmax_channel(pred).astype('int32').asnumpy().reshape(-1)
  File "/home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/ndarray/ndarray.py", line 1972, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/base.py", line 251, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:31:25] src/operator/nn/./convolution-inl.h:179: Check failed: req[conv::kOut] == kWriteTo (0 vs. 1) 

Stack trace returned 10 entries:
[bt] (0) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x55) [0x7f0ee520ba05]
[bt] (1) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f0ee520c538]
[bt] (2) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::op::ConvolutionOp<mshadow::gpu, float>::Forward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0xdf) [0x7f0ee7ba9aaf]
[bt] (3) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(void mxnet::op::ConvolutionCompute<mshadow::gpu>(nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0xb0a) [0x7f0ee7b95f6a]
[bt] (4) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::exec::FComputeExecutor::Run(mxnet::RunContext, bool)+0x59) [0x7f0ee72054b9]
[bt] (5) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(+0x2c53a27) [0x7f0ee71aea27]
[bt] (6) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x8e5) [0x7f0ee77905b5]
[bt] (7) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0xeb) [0x7f0ee77a6f1b]
[bt] (8) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#4}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>&&)+0x4e) [0x7f0ee77a717e]
[bt] (9) /home/yang/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet-1.3.1-py3.6.egg/mxnet/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<dmlc::ManualEvent>)> (std::shared_ptr<dmlc::ManualEvent>)> >::_M_run()+0x4a) [0x7f0ee778fbba]

```

Looing forward to your reply, Thanks in advance! @xchani @RogerChern

**Comment by qixuxiang** [comment]
Thank you and looking forward to new docker image ^_^

**Comment by RogerChern** [comment]
@qixuxiang cuda 10.0 docker image is available from `rogerchen/simpledet:cuda10`

**Comment by qixuxiang** [comment]
Awesome!My big brother, You are a true life-saver!! @RogerChern
