### ISSUE TITLE
training error with two gpus

### ISSUE THREAD

**Issue by qilicun** [TuSimple/simpledet#85]
Hi,
First, thank you for open this amazing framework which could help me a lot!
I followed in INSTALL procedure and installed all the requirement. I have a 2 1080TI  gpus, so I modified gpus from [0,1,2,3,4,5,6,7] to [0,1] in ``config/tridentnet_r50v2c4_c5_1x.py``, but got the following error. Can anyone help me with this. Thanks in advance!

```sh
Traceback (most recent call last):
  File "detection_train.py", line 229, in <module>
    train_net(parse_args())
  File "detection_train.py", line 213, in train_net
    num_epoch=end_epoch
  File "/home/program/simpledet/core/detection_module.py", line 995, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/program/simpledet/core/detection_module.py", line 783, in update_metric
    self._exec_group.update_metric(eval_metric, labels, pre_sliced)
  File "/home/.local/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/module/executor_group.py", line 639, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/.local/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/metric.py", line 350, in update_dict
    metric.update_dict(labels, preds)
  File "/home//.local/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/metric.py", line 133, in update_dict
    self.update(label, pred)
  File "/home/program/simpledet/core/detection_metric.py", line 41, in update
    pred_label = mx.ndarray.argmax_channel(pred).astype('int32').asnumpy().reshape(-1)
  File "/home/.local/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1995, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/.local/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:39:27] include/mxnet/tuple.h:202: Check failed: i >= 0 && i < ndim(): index = 0 must be in range [0, -1)
Stack trace:
  [bt] (0) /home/.local/lib/python3.5/site-packages/mxnet-1.5.0-py3.5.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x32) [0x7f4bd9b51102]

```

**Comment by qilicun** [comment]
solve by https://github.com/TuSimple/simpledet/issues/83
