### ISSUE TITLE
question about singularity

### ISSUE THREAD

**Issue by heiyuxiaokai** [TuSimple/simpledet#90]
The docker file works well.
I use the singularity img: https://simpledet-model.oss-cn-beijing.aliyuncs.com/simpledet.img
when the path is "/home/software/simpledet":
python3 can import mxnet, but can not import mxnet.mertic
when the path is "/home/software" of "/home/software/simpledet/any other dictory":
python3 can not import both mxnet and mxnet.metric

I tried make singularity img from the docker file you provide, but I met the same problem.
How can I use simpledet on other machine without making mxnet if I use singularity.
That's the information :
Singularity> python3 detection_train.py --config config/faster_r101v1_fpn_1x.py
Traceback (most recent call last):
  File "detection_train.py", line 12, in <module>
    from core.detection_module import DetModule
  File "/home/fw/Softwares/simpledet/core/detection_module.py", line 29, in <module>
    from mxnet import metric
ImportError: cannot import name 'metric'
Singularity>

**Comment by heiyuxiaokai** [comment]
When I run this command:
nvidia-docker run -it -v /home/fw/Softwares/simpledet:/home/fw/Softwares/simpledet rogerchen/simpledet:cuda9 zsh
the python enviroment:
PYTHON_CONFIGURE_OPTS  python3                python3.6-config     
python                 python3-config         python3.6-gdb.py     
python-config          python3.5              python3.6m           
python2                python3.5m             python3.6m-config    
python2.7              python3.6              python3m
When I run this command:
nvidia-docker run -it -v /home/fw/Softwares/simpledet:/home/fw/Softwares/simpledet rogerchen/simpledet:cuda9 /bin/bash
the python enviroment:
python      python2.7   python3.5   python3m    
python2     python3     python3.5m

the python 3.5 is same as my machine, perhaps singularity is same. When I use singularity shell, the python is:
python      python2.7   python3.5   python3m    
python2     python3     python3.5m

how can I solve it?

**Comment by heiyuxiaokai** [comment]
It has been solved. My machine us bash instead of zsh. Remaking the docker image and singularity image works.
