### ISSUE TITLE
python detection_train.py --config config/tridentnet_r101v2c4_c5_1x.py

### ISSUE THREAD

**Issue by shocho3858** [TuSimple/simpledet#92]
```
Traceback (most recent call last):
  File "detection_train.py", line 229, in <module>
    train_net(parse_args())
  File "detection_train.py", line 213, in train_net
    num_epoch=end_epoch
  File "/root/workspace/simpledet/core/detection_module.py", line 995, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/root/workspace/simpledet/core/detection_module.py", line 783, in update_metric
    self._exec_group.update_metric(eval_metric, labels, pre_sliced)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/module/executor_group.py", line 639, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/metric.py", line 350, in update_dict
    metric.update_dict(labels, preds)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/metric.py", line 133, in update_dict
    self.update(label, pred)
  File "/root/workspace/simpledet/core/detection_metric.py", line 41, in update
    pred_label = mx.ndarray.argmax_channel(pred).astype('int32').asnumpy().reshape(-1)
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/ndarray/ndarray.py", line 1995, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/mxnet-1.5.0-py3.6.egg/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [07:46:04] include/mxnet/tuple.h:202: Check failed: i >= 0 && i < ndim(): index = 0 must be in range [0, -1)
```

I also print out the shape of some variables which may help to solve this problem. 

1. the model outputs:

```
[('rpn_cls_loss_output', (3, 2, 15, 50, 75)), ('rpn_reg_loss_output', (3, 60, 50, 75)), ('bbox_cls_loss_output', (384, 81)), ('bbox_reg_loss_output', (384, 8)), ('bbox_label_blockgrad_output', (3, 128))]
```
2. the data batch shapes:
```
data_iter = iter(train_data)
data_batch = next(data_iter)
for i in data_batch.label:
    print(i.shape)
```
 gives: `(8, 3, 56250), (8, 3, 60, 50, 75), (8, 3, 60, 50, 75)`.

**Comment by RogerChern** [comment]
Please refer to #83
